<?php
namespace app\models;

use app\core\Application;
use app\core\DbModel;

/**
 * @author Mohamed A. Shehata <elza3ym@icloud.com>
 **/
class Blog extends DbModel {
    public string $title = '';
    public string $description = '';
    public string $image = '';

    public int $userId = 0;
    public function fillables(): array {
        return [
            'title', 'description', 'image', 'userId'
        ];
    }

    public function rules(): array {
        return [
            'title' => [
                self::RULE_REQUIRED,
                self::RULE_MIN => [
                    self::RULE_MIN => 8
                ]
            ],
            'description' => [
                self::RULE_REQUIRED,
                self::RULE_MIN => [
                    self::RULE_MIN => 8
                ]
            ],
        ];
    }

    public function labels(): array {
        return [
            'title' => 'Title',
            'description' => 'Blog Description',
            'image' => 'Image URL',
        ];
    }

    public static function tableName(): string {
        return 'blogs';
    }

    public static function primaryKey(): string {
        return 'id';
    }

    public function save() {
        $this->userId = Application::$app->user->id;
        if (empty($this->image)) {
            $this->image = 'https://placeholder.com/';
        }
        return parent::save(); // TODO: Change the autogenerated stub
    }

    public static function getUser($user_id) {
        return User::findOne(['id' => $user_id]);
    }

    public function getShortDescription(){
        if (strlen($this->description) > 1000) {
            return substr($this->description, 0, 1000-3) . '...';
        }
    }

}